[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 0 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.6
blur = true
option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"
size = 16
